from borb.pdf import Document,DropDownList,MultiColumnLayout,FormField,Table,TextBox,TextArea,Page,PDF,Paragraph,LinkAnnotation,LineArt,SingleColumnLayout,Image,MapOfTheWorld,CheckBox,Button,FlexibleColumnWidthTable

pdfGenerator = Document()
newPage = Page()
pdfGenerator.append_page(newPage)
currentLayout = SingleColumnLayout(newPage)
currentLayout.append_layout_element(Paragraph("This is a test PDF document created using borb library in Python."))
currentLayout.append_layout_element(TextBox(field_name='Name'))
currentLayout.append_layout_element(DropDownList(field_name='Gender',options=['Male','Female','Other']))
currentLayout.append_layout_element(Button(text='Submit',))
# currentLayout.append_layout_element(LinkAnnotation("https://www.google.com","Google"))
# form = FormField()
with open(r'c:\Users\WELCOME\Project-TPM\Profile Images\98f41876-6a77-424e-9d1b-946e27546799.jpg', 'rb') as image_file:image_data = image_file.read()
currentLayout.append_layout_element(Image(image_data,size=(150,150)))
currentLayout.append_layout_element(MapOfTheWorld())
table = FlexibleColumnWidthTable(number_of_columns=2,number_of_rows=2)
table.append_layout_element(Paragraph("Name"))
table.append_layout_element(Paragraph("Age"))
table.append_layout_element(Paragraph("Daniel"))
table.append_layout_element(Paragraph("22"))
# table.append_layout_element(TextBox(field_name='Name',))
currentLayout.append_layout_element(table)
# table.append_layout_element(Paragraph('Name'))
# table.append_layout_element(Paragraph('Age'))
# table.append_layout_element(Paragraph('Occupation'))
# table.append_layout_element(Paragraph('Home Town'))
# currentLayout.append_layout_element(table)
PDF.write(pdfGenerator, "AdvPdf.pdf")